disabled_rules:
  - type_name
  - identifier_name
  - switch_case_alignment
  - cyclomatic_complexity # Too many false alarms for enum conversion switch statements
  - redundant_optional_initialization
  - closure_parameter_position
  - opening_brace
  - nesting # Sometimes it just makes sense to nest 2 levels deep
  - trailing_comma # Conflicts with code-format
  - file_length
  - force_cast # Required a lot in backend implementations
  - function_body_length

line_length: 140
type_body_length: 400

included:
  - Sources
  - Examples
excluded:
  - Sources/AppCode/Builders/ViewBuilder.code
  - Sources/AppCode/Builders/SceneBuilder.code
  - Sources/AppCode/Builders/TableRowBuilder.code
  - Sources/AppCode/Views/TupleView.code
  - Sources/AppCode/Views/TupleViewChildren.code
  - Sources/AppCode/Views/TableRowContent.code
  - Sources/AppCode/Scenes/TupleScene.code
  - Sources/Gtk/Generated
  - Examples/.build
