//===----------------------------------------------------------------------===//
//
// Copyright (c) 2025 NeXTHub Corporation. All rights reserved.
// DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// version 2 for more details (a copy is included in the LICENSE file that
// accompanied this code).
//
// Author(-s): Tunjay Akbarli
// Creation Date: Saturday, May 10, 2025.
//
//===----------------------------------------------------------------------===//

// Size is passed in via specialization constant.
layout(local_size_x_id = 0) in;

layout(std430) buffer;

layout(binding = 1) writeonly buffer OutputData {
  uint data[];
}
output_data;

void main() {
  uint ident = gl_GlobalInvocationID.x;
  output_data.data[ident] = ident;
}
