//===----------------------------------------------------------------------===//
//
// Copyright (c) 2025 NeXTHub Corporation. All rights reserved.
// DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// version 2 for more details (a copy is included in the LICENSE file that
// accompanied this code).
//
// Author(-s): Tunjay Akbarli
// Creation Date: Saturday, May 10, 2025.
//
//===----------------------------------------------------------------------===//

import 'dart:io';

import 'package:path/path.dart' as path;

String _flutterBuildDirectoryPath() {
  assert(Platform.environment.containsKey('APPCODE_BUILD_DIRECTORY'));

  return Platform.environment['APPCODE_BUILD_DIRECTORY']!;
}

const String _testPath = 'gen/flutter/lib/ui/fixtures/shaders';

/// Gets the [Directory] shader files that are generated by `lib/ui/fixtures/shaders`.
///
/// `folderName` is a leaf folder within the generated directory.
Directory shaderDirectory(String leafFolderName) {
  return Directory(
    path.joinAll(<String>[
      ...path.split(_flutterBuildDirectoryPath()),
      ...path.split(_testPath),
      leafFolderName,
    ]),
  );
}
